sitename: Bolt in Alibaba Cloud
payoff: My first Bolt site in Alicloud

theme: bolt-theme

locale: en_AU

maintenance_mode: false
maintenance_template: maintenance_default.html.twig

cron_hour: 3

homepage: page/1
homepage_template: index.html.twig

notfound: block/404-not-found

record_template: record.html.twig

listing_template: listing.html.twig
listing_records: 6
listing_sort: datepublish DESC

taxonomy_sort: DESC

search_results_template: search.html.twig
search_results_records: 10

add_jquery: false

recordsperpage: 10

caching:
    config: false
    templates: false
    request: false
    duration: 10
    authenticated: false
    thumbnails: false
    translations: false

changelog:
    enabled: false

thumbnails:
    default_thumbnail: [ 160, 120 ]
    default_image: [ 1000, 750 ]
    quality: 80
    cropping: crop
    notfound_image: bolt_assets://img/default_notfound.png
    error_image: bolt_assets://img/default_error.png
    save_files: false
    allow_upscale: false
    exif_orientation: true
    only_aliases: false

htmlcleaner:
    allowed_tags: [ div, span, p, br, hr, s, u, strong, em, i, b, li, ul, ol, mark, blockquote, pre, code, tt, h1, h2, h3, h4, h5, h6, dd, dl, dt, table, tbody, thead, tfoot, th, td, tr, a, img, address, abbr, iframe, caption, sub, super, figure, figcaption ]
    allowed_attributes: [ id, class, style, name, value, href, src, alt, title, width, height, frameborder, allowfullscreen, scrolling, target, colspan, rowspan ]

accept_file_types: [ twig, html, js, css, scss, gif, jpg, jpeg, png, ico, zip, tgz, txt, md, doc, docx, pdf, epub, xls, xlsx, ppt, pptx, mp3, ogg, wav, m4a, mp4, m4v, ogv, wmv, avi, webm, svg]

debug: true
debug_show_loggedoff: false
debug_permission_audit_mode: false
debug_error_level: -1
debug_error_use_symfony: false
debug_trace_argument_limit: 4

debuglog:
    enabled: false
    filename: bolt-debug.log
    level: DEBUG

wysiwyg:
    images: false
    anchor: false
    tables: false
    fontcolor: false
    align: false
    subsuper: false
    embed: false
    underline: false
    ruler: false
    strike: false
    blockquote: false
    codesnippet: false
    specialchar: false
    ck:
        autoParagraph: true
        disableNativeSpellChecker: true
        allowNbsp: false

liveeditor: false

cookies_use_remoteaddr: true
cookies_use_browseragent: false
cookies_use_httphost: true

cookies_lifetime: 1209600

cookies_domain:

hash_strength: 10

compatibility:
    template_view: true
    setcontent_legacy: true
